### PR TITLE
TS transform breaks imports in templates

### PR DESCRIPTION
**Pull request by ef4**
`@babel/plugin-transform-typescript` removes unused imports because it assumes they're types. That's how tsc also behaves so it's at least understandable.

However, it doesn't respect the fact that our plugin is *emitting* code that *does* use the imports. Maddeningly, they insist on doing the removal in [Program.enter](https://github.com/babel/babel/blob/2ce1d11b718ae45da8daea1518450435e240ed0e/packages/babel-plugin-transform-typescript/src/index.ts#L374), an unnecessarily painful place to do it, since it won't even wait to see if another plugin might introduce new bindings (which we could be careful to do, as in [here](https://github.com/ef4/babel-import-util/blob/ecc6d124b650984d87e16465ab8dc5585fa4dd1c/src/index.ts#L93C5-L96C7). 

This adds a failing test.

There are a few options to fix this. *If* we refactor our plugin to do its work in Program.enter *and* insist that it needs to com e before typescript we can get in early enough to avoid. But that is pretty gross.

Alternatively, we could require that people set `onlyRemoveTypeImports: true` in `@babel/plugin-transform-typescript`. That avoids the problem, but it requires them to be careful to always annotate their type-only imports explicitly.

### CODE REVIEW

**Comment by ef4** [comment]
This fixes the tests, what's not clear is if we really think it's OK to always require this:

```diff

diff --git a/__tests__/tests.ts b/__tests__/tests.ts
index 9d5c8fa..035e87d 100644
--- a/__tests__/tests.ts
+++ b/__tests__/tests.ts
@@ -1792,7 +1792,7 @@ describe('htmlbars-inline-precompile', function () {
             targetFormat: 'hbs',
           },
         ],
-        TransformTypescript,
+        [TransformTypescript, { onlyRemoveTypeImports: true } as any],
       ];
 
       let transformed = transform(
@@ -1820,7 +1820,7 @@ describe('htmlbars-inline-precompile', function () {
             targetFormat: 'wire',
           },
         ],
-        TransformTypescript,
+        [TransformTypescript, { onlyRemoveTypeImports: true } as any],
       ];
 
       let transformed = transform(
```

**Comment by NullVoxPopuli** [comment]
I think we should probably update our base tsconfig to require `type` be specified, like svelte has done: https://github.com/tsconfig/bases/blob/main/bases/svelte.json#L14

This should (:crossed_fingers: ) help mitigate an issues people would have with `onlyRemoveTypeImports`?

The option is new enough where only two configs have it: https://github.com/search?q=repo%3Atsconfig%2Fbases%20verbatimModuleSyntax&type=code

but the rest of the bases are combinable with others, and the ember one isn't so much due to :sparkles: history :sparkles: -- we could probably tell ember folks to extend from [bases/esm, bases/ember] eventually tho

**Comment by patricklx** [comment]
I think another option would also to re-add the imports on program:exit? It will rerun all visitors, but then it would also have the bindings and should not be removed

**Comment by patricklx** [comment]
I think with plugin pre function you can access state.file.ast, make a local copy of the imports and re-add the ones used by the templates later

**Pull request closed without merging**
