### PR TITLE
Preserve used imports

### PR DESCRIPTION
**Pull request by ef4**
Builds off https://github.com/emberjs/babel-plugin-ember-template-compilation/pull/31 to fix https://github.com/emberjs/babel-plugin-ember-template-compilation/pull/30.

Instead of keeping *everything* as in https://github.com/emberjs/babel-plugin-ember-template-compilation/pull/31 (which is not safe in general), we use the `pre` to take a snapshot of available imports and then only when we discover that a template wants to use a name that is not in scope do we check if it was in the original set of available imports and reintroduce an import for it.

### CODE REVIEW

**Comment by ef4** [comment]
I confirmed locally that this PR fixes https://github.com/ember-template-imports/ember-template-imports/pull/211

**Comment by patricklx** [comment]
Does this also work with amd transform? Would be good to have a test for it too

**Comment by ef4** [comment]
This PR didn't change anything about the timing of when we add imports. We were [already](https://github.com/emberjs/babel-plugin-ember-template-compilation/blob/5fceb59b20bc8cf688d8f18fefde1c774eaa1b76/src/plugin.ts#L529) [adding](https://github.com/emberjs/babel-plugin-ember-template-compilation/blob/5fceb59b20bc8cf688d8f18fefde1c774eaa1b76/src/plugin.ts#L539) [imports](https://github.com/emberjs/babel-plugin-ember-template-compilation/blob/5fceb59b20bc8cf688d8f18fefde1c774eaa1b76/src/plugin.ts#L544) in a bunch of places within the expression-level visitors.

**Comment by patricklx** [comment]
I also saw now that amd transform runs an program:exit

**Pull request merged**
