### PR TITLE
fix ts import issue with fcct

### PR DESCRIPTION
**Pull request by patricklx**

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
Firstly, I really appreciate you trying to fix this problem!!!


however, I don't think we want to go down this route -- "two wrongs don't make a right" -- @ef4 is working on fixing the babel typescript plugin.

**Comment by patricklx** [comment]
The only downside is that it also does not remove unused type imports. 
If they are annotated with `type` it works correctly

**Comment by ef4** [comment]
I agree that we might need to do our own `pre` hack if fixes in typescript-transform turn out to be hard to land. And yeah, I had forgotten how annoying amd-transform is for these situations (embroider doesn't use it, but we still need to care about classic builds that do).

I think we can probably extend the ideas here to be more targeted though. For example:

1. `pre` could capture a list of imports. 
2. When we're processing each template, *we already know what names it needs*. For each name:
   - if the name is not in scope
     - and the name was in the original list of imports
       - then we re-insert an import for that name.

This would allow all the normal removal of imports to take its usual course, and limit our changes to precisely the names that we know we need that other plugins can't know that we need.

**Comment by ef4** [comment]
I continued this branch in #32.

**Pull request closed without merging**
